feat(YouTube Music): add support version `6.20.51` (#57)
* feat(YouTube Music): add support version `6.20.51`

* Downgrade minSdk to 21
* fix(Player components): `Hide audio video switch toggle` causes a crash on 6.20
* fix(Player components): Play button turns black on Android 5.x if `Restore old player background` is disabled

* feat: apply code review suggestions

* feat: apply code review suggestions

* fix java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/ContentProviderClient;

* fix noinspection id

* Use AlertDialog.THEME_DEVICE_DEFAULT_DARK

Co-authored-by: inotia00 <108592928+inotia00@users.noreply.github.com>

* chore: lint code

---------

Co-authored-by: inotia00 <108592928+inotia00@users.noreply.github.com>